destination = "/root/backups"

[[backup]]
container = "default-betula-k1pscr-betula-1"
volume = "/var/lib/docker/volumes/default-betula-k1pscr_betula_data/_data"
keep = 5
sqlite = "links.betula"

[[backup]]
container = "readeck"
volume = "/var/lib/docker/volumes/default-readeck-garlke_readeck-data/_data"
keep = 5
sqlite = "data/db.sqlite3"
