destination = "/root/backups"

[[backup]]
service = "auth-postgres-ht2mkp"
volume = "/var/lib/docker/volumes/auth-postgres-ht2mkp-data/_data"
keep = 5

[[backup]]
container = "sara-kv-jjjwil-app-1"
volume = "/var/lib/docker/volumes/sara-kv-jjjwil_app-data/_data"
keep = 10
sqlite = "db.sqlite3"
data = false

[[backup]]
container = "vaultwarden"
volume = "/var/lib/docker/volumes/platform-vaultwarden-pkm1vh_vaultwarden-data/_data"
keep = 7
sqlite = "db.sqlite3"

[[backup]]
container = "crowdsec-vgalbx-crowdsec-1"
keep = 5

[[backup.volumes]]
volume = "/var/lib/docker/volumes/crowdsec-vgalbx_crowdsec-db/_data"
sqlite = "crowdsec.db"
name = "crowdsec-db"

[[backup.volumes]]
volume = "/var/lib/docker/volumes/crowdsec-vgalbx_crowdsec-config/_data"
name = "crowdsec-config"

[[backup]]
container = "uptime-kuma"
volume = "/var/lib/docker/volumes/monitoring-uptimekuma-rvtafy_uptime-kuma/_data"
keep = 2
sqlite = "kuma.db"
data = false
